# Generated by Django 4.2.7 on 2025-08-13 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kateqoriya adı')),
                ('description', models.TextField(blank=True, verbose_name='Təsvir')),
                ('color', models.CharField(default='#059669', max_length=7, verbose_name='Rəng')),
                ('icon', models.CharField(default='fas fa-calendar', max_length=50, verbose_name='İkon')),
            ],
            options={
                'verbose_name': 'Tədbir Kateqoriyası',
                'verbose_name_plural': 'Tədbir Kateqoriyaları',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlıq')),
                ('description', models.TextField(verbose_name='Təsvir')),
                ('image', models.ImageField(upload_to='events/', verbose_name='Şəkil')),
                ('date', models.DateTimeField(verbose_name='Tarix və vaxt')),
                ('duration', models.IntegerField(help_text='Dəqiqə ilə', verbose_name='Müddət')),
                ('location', models.CharField(max_length=200, verbose_name='Yer')),
                ('age_group', models.CharField(choices=[('0-3', '0-3 yaş'), ('3-6', '3-6 yaş'), ('6-9', '6-9 yaş'), ('9-12', '9-12 yaş'), ('12+', '12+ yaş'), ('all', 'Bütün yaşlar')], max_length=10, verbose_name='Yaş qrupu')),
                ('max_participants', models.IntegerField(verbose_name='Maksimum iştirakçı sayı')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qiymət')),
                ('status', models.CharField(choices=[('upcoming', 'Gələcək'), ('ongoing', 'Davam edir'), ('completed', 'Tamamlandı'), ('cancelled', 'Ləğv edildi')], default='upcoming', max_length=20, verbose_name='Status')),
                ('requirements', models.TextField(blank=True, verbose_name='Tələblər')),
                ('what_to_bring', models.TextField(blank=True, verbose_name='Nə gətirmək lazımdır')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.eventcategory', verbose_name='Kateqoriya')),
            ],
            options={
                'verbose_name': 'Tədbir',
                'verbose_name_plural': 'Tədbirlər',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EventReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Qiymət')),
                ('comment', models.TextField(verbose_name='Şərh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='events.event', verbose_name='Tədbir')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'Tədbir Rəyi',
                'verbose_name_plural': 'Tədbir Rəyləri',
                'ordering': ['-created_at'],
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Gözləyir'), ('confirmed', 'Təsdiqləndi'), ('cancelled', 'Ləğv edildi'), ('completed', 'Tamamlandı')], default='pending', max_length=20, verbose_name='Status')),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='Rezervasiya tarixi')),
                ('notes', models.TextField(blank=True, verbose_name='Qeydlər')),
                ('attended', models.BooleanField(default=False, verbose_name='İştirak etdi')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='membership.child', verbose_name='Uşaq')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='events.event', verbose_name='Tədbir')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'Rezervasiya',
                'verbose_name_plural': 'Rezervasiyalar',
                'ordering': ['-booking_date'],
                'unique_together': {('event', 'child')},
            },
        ),
    ]
