# Generated by Django 5.2.5 on 2025-11-13 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlıq')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(max_length=300, verbose_name='Qısa Təsvir')),
                ('description', models.TextField(verbose_name='Təsvir')),
                ('icon', models.ImageField(upload_to='services/icons/', verbose_name='İkon')),
                ('image', models.ImageField(upload_to='services/', verbose_name='Şəkil')),
                ('detail_image', models.ImageField(upload_to='services/detail/', verbose_name='Detail Şəkil')),
                ('service_type', models.CharField(choices=[('featured', 'Seçilmiş Xidmət'), ('standard', 'Standart Xidmət'), ('value', 'Dəyər Xidməti')], default='standard', max_length=20, verbose_name='Xidmət Tipi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma Tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə Tarixi')),
            ],
            options={
                'verbose_name': 'Xidmət',
                'verbose_name_plural': 'Xidmətlər',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServicePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breadcrumb_title', models.CharField(default='Xidmətlər', max_length=200, verbose_name='Breadcrumb Başlıq')),
                ('breadcrumb_description', models.TextField(default='Alisa Club uşaqlar üçün əyləncəli və öyrədici fəaliyyətlər təqdim edir', max_length=500, verbose_name='Breadcrumb Təsvir')),
                ('breadcrumb_image', models.ImageField(blank=True, null=True, upload_to='services/breadcrumb/', verbose_name='Breadcrumb Arxa Fon')),
                ('top_section_title', models.CharField(default='Uşağınızı İndi Proqrama Qeydiyyatdan Keçirin!', max_length=300, verbose_name='Üst Bölmə Başlığı')),
                ('top_section_description', models.TextField(default='Alisa Club-da hər uşaq üçün açıq qapı siyasəti mövcuddur və bütün uşaqlar üçün pulsuz sınaq dərsi təklif olunur.', verbose_name='Üst Bölmə Təsviri')),
                ('middle_section_subtitle', models.CharField(default='Bizim Təklif Etdiyimiz Xidmətlər', max_length=200, verbose_name='Orta Bölmə Alt Başlığı')),
                ('middle_section_title', models.CharField(default='Uşağınızı fəaliyyətlərdə düzgün istiqamətləndirmək və dəstək olmaq üçün buradayıq', max_length=300, verbose_name='Orta Bölmə Başlığı')),
                ('values_section_subtitle', models.CharField(default='Niyə Alisa Club?', max_length=200, verbose_name='Dəyərlər Bölməsi Alt Başlığı')),
                ('values_section_title', models.CharField(default='Əsas Dəyərlərimiz', max_length=300, verbose_name='Dəyərlər Bölməsi Başlığı')),
                ('values_section_description', models.TextField(default='Alisa Club-da uşaqların inkişafını diqqətlə izləyir və onlara hər yaşda əyləncəli və öyrədici fəaliyyətlər təqdim edirik.', verbose_name='Dəyərlər Bölməsi Təsviri')),
                ('cta_title', models.CharField(default='Gəlin birlikdə möhtəşəm anlar yaradaq', max_length=300, verbose_name='CTA Başlığı')),
                ('cta_description', models.TextField(default='Uşağınızın inkişafı, təlimi və klubdakı fəaliyyətləri barədə ən son məlumatları, dəstək və tövsiyələri əldə edin.', verbose_name='CTA Təsviri')),
                ('cta_button_text', models.CharField(default='Üzv Ol', max_length=50, verbose_name='CTA Düymə Mətni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə Tarixi')),
            ],
            options={
                'verbose_name': 'Xidmətlər Səhifə Parametrləri',
                'verbose_name_plural': 'Xidmətlər Səhifə Parametrləri',
            },
        ),
        migrations.CreateModel(
            name='ServiceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Sual')),
                ('answer', models.TextField(verbose_name='Cavab')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='services.service', verbose_name='Xidmət')),
            ],
            options={
                'verbose_name': 'Xidmət FAQ',
                'verbose_name_plural': 'Xidmət FAQ-lar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_text', models.CharField(max_length=300, verbose_name='Xüsusiyyət')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.service', verbose_name='Xidmət')),
            ],
            options={
                'verbose_name': 'Xidmət Xüsusiyyəti',
                'verbose_name_plural': 'Xidmət Xüsusiyyətləri',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=100, verbose_name='Sessiya Adı')),
                ('time_range', models.CharField(max_length=100, verbose_name='Vaxt Aralığı')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='services.service', verbose_name='Xidmət')),
            ],
            options={
                'verbose_name': 'Xidmət Cədvəli',
                'verbose_name_plural': 'Xidmət Cədvəlləri',
                'ordering': ['order', 'id'],
            },
        ),
    ]
