# Generated by Django 5.2.5 on 2025-11-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='servicepagesettings',
            name='values_section_description',
        ),
        migrations.RemoveField(
            model_name='servicepagesettings',
            name='values_section_subtitle',
        ),
        migrations.RemoveField(
            model_name='servicepagesettings',
            name='values_section_title',
        ),
        migrations.AddField(
            model_name='service',
            name='icon_path',
            field=models.CharField(default='assets/img/icon/sr-1-1.svg', help_text='Məsələn: assets/img/icon/sr-1-1.svg', max_length=200, verbose_name='İkon Yolu'),
        ),
        migrations.AddField(
            model_name='service',
            name='show_in_featured',
            field=models.BooleanField(default=False, verbose_name='Seçilmiş Xidmətlərdə Göstər'),
        ),
        migrations.AddField(
            model_name='service',
            name='show_in_standard',
            field=models.BooleanField(default=True, verbose_name='Standart Xidmətlərdə Göstər'),
        ),
        migrations.AddField(
            model_name='service',
            name='show_in_values',
            field=models.BooleanField(default=False, verbose_name='Dəyərlər Bölməsində Göstər'),
        ),
    ]
