# Generated by Django 5.2.5 on 2025-11-25 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_service_icon_remove_service_service_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Təsvir'),
        ),
        migrations.AlterField(
            model_name='service',
            name='detail_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/detail/', verbose_name='Detail Şəkil'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_path',
            field=models.CharField(blank=True, default='assets/img/icon/sr-1-1.svg', help_text='Məsələn: assets/img/icon/sr-1-1.svg', max_length=200, null=True, verbose_name='İkon Yolu'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Qısa Təsvir'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='servicefaq',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Cavab'),
        ),
        migrations.AlterField(
            model_name='servicefaq',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Sıra'),
        ),
        migrations.AlterField(
            model_name='servicefaq',
            name='question',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Sual'),
        ),
        migrations.AlterField(
            model_name='servicefaq',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='services.service', verbose_name='Xidmət'),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='feature_text',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Xüsusiyyət'),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Sıra'),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.service', verbose_name='Xidmət'),
        ),
        migrations.AlterField(
            model_name='servicepagesettings',
            name='breadcrumb_description',
            field=models.TextField(blank=True, default='Alisa Club uşaqlar üçün əyləncəli və öyrədici fəaliyyətlər təqdim edir', max_length=500, null=True, verbose_name='Breadcrumb Təsvir'),
        ),
        migrations.AlterField(
            model_name='servicepagesettings',
            name='breadcrumb_title',
            field=models.CharField(blank=True, default='Xidmətlər', max_length=200, null=True, verbose_name='Breadcrumb Başlıq'),
        ),
        migrations.AlterField(
            model_name='servicepagesettings',
            name='cta_button_text',
            field=models.CharField(blank=True, default='Üzv Ol', max_length=50, null=True, verbose_name='CTA Düymə Mətni'),
        ),
        migrations.AlterField(
            model_name='servicepagesettings',
            name='cta_description',
            field=models.TextField(blank=True, default='Uşağınızın inkişafı, təlimi və klubdakı fəaliyyətləri barədə ən son məlumatları, dəstək və tövsiyələri əldə edin.', null=True, verbose_name='CTA Təsviri'),
        ),
        migrations.AlterField(
            model_name='servicepagesettings',
            name='cta_title',
            field=models.CharField(blank=True, default='Gəlin birlikdə möhtəşəm anlar yaradaq', max_length=300, null=True, verbose_name='CTA Başlığı'),
        ),
        migrations.AlterField(
            model_name='servicepagesettings',
            name='middle_section_subtitle',
            field=models.CharField(blank=True, default='Bizim Təklif Etdiyimiz Xidmətlər', max_length=200, null=True, verbose_name='Orta Bölmə Alt Başlığı'),
        ),
        migrations.AlterField(
            model_name='servicepagesettings',
            name='middle_section_title',
            field=models.CharField(blank=True, default='Uşağınızı fəaliyyətlərdə düzgün istiqamətləndirmək və dəstək olmaq üçün buradayıq', max_length=300, null=True, verbose_name='Orta Bölmə Başlığı'),
        ),
        migrations.AlterField(
            model_name='servicepagesettings',
            name='top_section_description',
            field=models.TextField(blank=True, default='Alisa Club-da hər uşaq üçün açıq qapı siyasəti mövcuddur və bütün uşaqlar üçün pulsuz sınaq dərsi təklif olunur.', null=True, verbose_name='Üst Bölmə Təsviri'),
        ),
        migrations.AlterField(
            model_name='servicepagesettings',
            name='top_section_title',
            field=models.CharField(blank=True, default='Uşağınızı İndi Proqrama Qeydiyyatdan Keçirin!', max_length=300, null=True, verbose_name='Üst Bölmə Başlığı'),
        ),
        migrations.AlterField(
            model_name='serviceschedule',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Sıra'),
        ),
        migrations.AlterField(
            model_name='serviceschedule',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='services.service', verbose_name='Xidmət'),
        ),
        migrations.AlterField(
            model_name='serviceschedule',
            name='session_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sessiya Adı'),
        ),
        migrations.AlterField(
            model_name='serviceschedule',
            name='time_range',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vaxt Aralığı'),
        ),
    ]
