# Generated by Django 5.2.5 on 2025-11-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_description_alter_service_detail_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='detail_image',
            field=models.ImageField(blank=True, help_text='Tövsiyə olunan ölçü: 640x640 piksel', null=True, upload_to='services/detail/', verbose_name='Detail Şəkil'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Tövsiyə olunan ölçü: 300x380 piksel', null=True, upload_to='services/', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='servicepagesettings',
            name='breadcrumb_image',
            field=models.ImageField(blank=True, help_text='Tövsiyə olunan ölçü: 1920x520 piksel', null=True, upload_to='services/breadcrumb/', verbose_name='Breadcrumb Arxa Fon'),
        ),
    ]
