# Generated by Django 4.2.7 on 2025-08-13 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Paket Adı')),
                ('package_type', models.CharField(choices=[('basic', 'Əsas Paket'), ('premium', 'Premium Paket'), ('deluxe', 'Deluxe Paket')], max_length=20, verbose_name='Paket Növü')),
                ('description', models.TextField(verbose_name='Təsvir')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qiymət')),
                ('duration_hours', models.IntegerField(verbose_name='Müddət (saat)')),
                ('max_guests', models.IntegerField(verbose_name='Maksimum Qonaq Sayı')),
                ('includes', models.TextField(verbose_name='Daxil Olan Xidmətlər')),
                ('image', models.ImageField(blank=True, upload_to='birthday_packages/', verbose_name='Şəkil')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ad Günü Paketi',
                'verbose_name_plural': 'Ad Günü Paketləri',
            },
        ),
        migrations.CreateModel(
            name='BirthdayReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateField(verbose_name='Xatırlatma Tarixi')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Göndərildi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.child', verbose_name='Uşaq')),
            ],
            options={
                'verbose_name': 'Ad Günü Xatırlatması',
                'verbose_name_plural': 'Ad Günü Xatırlatmaları',
            },
        ),
        migrations.CreateModel(
            name='BirthdayBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(verbose_name='Rezervasiya Tarixi')),
                ('guest_count', models.IntegerField(verbose_name='Qonaq Sayı')),
                ('special_requests', models.TextField(blank=True, verbose_name='Xüsusi İstəklər')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Əlaqə Telefonu')),
                ('status', models.CharField(choices=[('pending', 'Gözləyir'), ('confirmed', 'Təsdiqləndi'), ('cancelled', 'Ləğv Edildi'), ('completed', 'Tamamlandı')], default='pending', max_length=20, verbose_name='Status')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ümumi Qiymət')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.child', verbose_name='Uşaq')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birthday.birthdaypackage', verbose_name='Paket')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Valideyn')),
            ],
            options={
                'verbose_name': 'Ad Günü Rezervasiyası',
                'verbose_name_plural': 'Ad Günü Rezervasiyaları',
                'ordering': ['-booking_date'],
            },
        ),
    ]
