# Generated by Django 5.2.5 on 2025-11-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='birthday/gallery/', verbose_name='Şəkil')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Başlıq')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma Tarixi')),
            ],
            options={
                'verbose_name': 'Doğum Günü Qalereyası',
                'verbose_name_plural': 'Doğum Günü Qalereyaları',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BirthdayPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breadcrumb_title', models.CharField(default='Doğum Günü Şənlikləri', max_length=200, verbose_name='Breadcrumb Başlıq')),
                ('breadcrumb_description', models.TextField(default='Uşaqlarınızın Doğum Gününü Alisa Club-da Unudulmaz Edin!', max_length=500, verbose_name='Breadcrumb Təsvir')),
                ('breadcrumb_image', models.ImageField(blank=True, null=True, upload_to='birthday/breadcrumb/', verbose_name='Breadcrumb Arxa Fon')),
                ('hero_subtitle', models.CharField(default='🎉 Uşaqlarınız üçün ən xoş günlər', max_length=200, verbose_name='Hero Alt Başlıq')),
                ('hero_title', models.CharField(default='Doğum Gününü Alisa Club-da Unudulmaz Edin!', max_length=300, verbose_name='Hero Başlıq')),
                ('hero_description', models.TextField(verbose_name='Hero Təsvir')),
                ('hero_image', models.ImageField(upload_to='birthday/hero/', verbose_name='Hero Şəkil')),
                ('hero_button_text', models.CharField(default='Rezervasiya Et', max_length=50, verbose_name='Hero Düymə Mətni')),
                ('hero_button_url', models.CharField(default='#contact-section', max_length=200, verbose_name='Hero Düymə URL')),
                ('gallery_subtitle', models.CharField(default='📷 Qalereya', max_length=200, verbose_name='Qalereyası Alt Başlıq')),
                ('gallery_title', models.CharField(default='Keçmiş Şənliklərdən Görüntülər', max_length=300, verbose_name='Qalereyası Başlıq')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə Tarixi')),
            ],
            options={
                'verbose_name': 'Doğum Günü Səhifə Parametrləri',
                'verbose_name_plural': 'Doğum Günü Səhifə Parametrləri',
            },
        ),
    ]
