# Generated by Django 5.2.5 on 2025-11-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=100, verbose_name='Uşağın Adı')),
                ('birth_date', models.DateField(verbose_name='Doğum Tarixi')),
                ('parent_name', models.CharField(max_length=100, verbose_name='Valideynin Adı')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('participants', models.PositiveIntegerField(blank=True, null=True, verbose_name='İştirakçı Sayı')),
                ('subscribe_to_events', models.BooleanField(default=False, verbose_name='Tədbirlərə Abunə')),
                ('is_read', models.BooleanField(default=False, verbose_name='Oxundu')),
                ('notes', models.TextField(blank=True, verbose_name='Qeydlər')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Göndərilmə Tarixi')),
            ],
            options={
                'verbose_name': 'Doğum Günü Rezervasiyası',
                'verbose_name_plural': 'Doğum Günü Rezervasiyaları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BirthdayReservationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(default='Doğum Günü Rezervasiyası', max_length=200, verbose_name='Bölmə Başlığı')),
                ('image_1', models.ImageField(upload_to='birthday/reservation/', verbose_name='Şəkil 1')),
                ('image_2', models.ImageField(upload_to='birthday/reservation/', verbose_name='Şəkil 2')),
                ('feature_1', models.CharField(default='Unudulmaz doğum günü təşkil edin', max_length=200, verbose_name='Xüsusiyyət 1')),
                ('feature_2', models.CharField(default='Rahat və əyləncəli mühit', max_length=200, verbose_name='Xüsusiyyət 2')),
                ('feature_3', models.CharField(default='Foto və video çəkiliş imkanı', max_length=200, verbose_name='Xüsusiyyət 3')),
                ('feature_4', models.CharField(default='Fərdi bəzək və proqram seçimi', max_length=200, verbose_name='Xüsusiyyət 4')),
                ('child_name_label', models.CharField(default='Uşağın adı', max_length=100, verbose_name='Uşağın Adı Etiketi')),
                ('birth_date_label', models.CharField(default='Doğum tarixi', max_length=100, verbose_name='Doğum Tarixi Etiketi')),
                ('parent_name_label', models.CharField(default='Valideynin adı', max_length=100, verbose_name='Valideynin Adı Etiketi')),
                ('email_label', models.CharField(default='Email', max_length=100, verbose_name='Email Etiketi')),
                ('phone_label', models.CharField(default='Telefon nömrəsi', max_length=100, verbose_name='Telefon Etiketi')),
                ('participants_label', models.CharField(default='İştirakçı sayı', max_length=100, verbose_name='İştirakçı Sayı Etiketi')),
                ('child_name_placeholder', models.CharField(default='Uşağın adını daxil edin', max_length=100, verbose_name='Uşağın Adı Placeholder')),
                ('parent_name_placeholder', models.CharField(default='Valideynin adını daxil edin', max_length=100, verbose_name='Valideynin Adı Placeholder')),
                ('email_placeholder', models.CharField(default='Email ünvanınızı daxil edin', max_length=100, verbose_name='Email Placeholder')),
                ('phone_placeholder', models.CharField(default='+994...', max_length=100, verbose_name='Telefon Placeholder')),
                ('participants_placeholder', models.CharField(default='Neçə uşaq iştirak edəcək?', max_length=100, verbose_name='İştirakçı Sayı Placeholder')),
                ('checkbox_label', models.CharField(default='Tədbirlə bağlı yeniliklərdən xəbərdar olmaq istəyirəm', max_length=200, verbose_name='Checkbox Etiketi')),
                ('submit_button_text', models.CharField(default='Rezerv et', max_length=50, verbose_name='Göndər Düyməsi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə Tarixi')),
            ],
            options={
                'verbose_name': 'Rezervasiya Bölməsi Parametrləri',
                'verbose_name_plural': 'Rezervasiya Bölməsi Parametrləri',
            },
        ),
    ]
