# Generated by Django 5.2.5 on 2025-08-15 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=100, verbose_name='Uşağın Adı')),
                ('child_age', models.IntegerField(verbose_name='Uşağın Yaşı')),
                ('event_date', models.DateField(verbose_name='Doğum Günü Tarixi')),
                ('guest_count', models.IntegerField(verbose_name='Qonaq Sayı')),
                ('theme', models.CharField(blank=True, choices=[('superhero', 'Superqəhrəmanlar'), ('princess', 'Şahzadələr'), ('space', 'Kosmik Macəra'), ('jungle', 'Cəngəllik Səyahəti'), ('other', 'Digər')], max_length=50, verbose_name='Mövzu')),
                ('notes', models.TextField(blank=True, verbose_name='Əlavə Qeydlər')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Əlaqə Telefonu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Valideyn')),
            ],
            options={
                'verbose_name': 'Ad Günü Sorğusu',
                'verbose_name_plural': 'Ad Günü Sorğuları',
            },
        ),
    ]
