# Generated by Django 5.2.5 on 2025-11-13 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0002_birthdayreservation_birthdayreservationsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthdayreservationsettings',
            name='birth_date_label',
        ),
        migrations.RemoveField(
            model_name='birthdayreservationsettings',
            name='checkbox_label',
        ),
        migrations.RemoveField(
            model_name='birthdayreservationsettings',
            name='child_name_label',
        ),
        migrations.RemoveField(
            model_name='birthdayreservationsettings',
            name='child_name_placeholder',
        ),
        migrations.RemoveField(
            model_name='birthdayreservationsettings',
            name='email_label',
        ),
        migrations.RemoveField(
            model_name='birthdayreservationsettings',
            name='email_placeholder',
        ),
        migrations.RemoveField(
            model_name='birthdayreservationsettings',
            name='parent_name_label',
        ),
        migrations.RemoveField(
            model_name='birthdayreservationsettings',
            name='parent_name_placeholder',
        ),
        migrations.RemoveField(
            model_name='birthdayreservationsettings',
            name='participants_label',
        ),
        migrations.RemoveField(
            model_name='birthdayreservationsettings',
            name='participants_placeholder',
        ),
        migrations.RemoveField(
            model_name='birthdayreservationsettings',
            name='phone_label',
        ),
        migrations.RemoveField(
            model_name='birthdayreservationsettings',
            name='phone_placeholder',
        ),
        migrations.RemoveField(
            model_name='birthdayreservationsettings',
            name='submit_button_text',
        ),
    ]
