# Generated by Django 5.2.5 on 2025-11-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0003_remove_birthdayreservationsettings_birth_date_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdaygallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='birthday/gallery/', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='birthdaygallery',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Sıra'),
        ),
        migrations.AlterField(
            model_name='birthdaygallery',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='birthdaypagesettings',
            name='breadcrumb_description',
            field=models.TextField(blank=True, default='Uşaqlarınızın Doğum Gününü Alisa Club-da Unudulmaz Edin!', max_length=500, null=True, verbose_name='Breadcrumb Təsvir'),
        ),
        migrations.AlterField(
            model_name='birthdaypagesettings',
            name='breadcrumb_title',
            field=models.CharField(blank=True, default='Doğum Günü Şənlikləri', max_length=200, null=True, verbose_name='Breadcrumb Başlıq'),
        ),
        migrations.AlterField(
            model_name='birthdaypagesettings',
            name='gallery_subtitle',
            field=models.CharField(blank=True, default='📷 Qalereya', max_length=200, null=True, verbose_name='Qalereyası Alt Başlıq'),
        ),
        migrations.AlterField(
            model_name='birthdaypagesettings',
            name='gallery_title',
            field=models.CharField(blank=True, default='Keçmiş Şənliklərdən Görüntülər', max_length=300, null=True, verbose_name='Qalereyası Başlıq'),
        ),
        migrations.AlterField(
            model_name='birthdaypagesettings',
            name='hero_button_text',
            field=models.CharField(blank=True, default='Rezervasiya Et', max_length=50, null=True, verbose_name='Hero Düymə Mətni'),
        ),
        migrations.AlterField(
            model_name='birthdaypagesettings',
            name='hero_button_url',
            field=models.CharField(blank=True, default='#contact-section', max_length=200, null=True, verbose_name='Hero Düymə URL'),
        ),
        migrations.AlterField(
            model_name='birthdaypagesettings',
            name='hero_description',
            field=models.TextField(blank=True, null=True, verbose_name='Hero Təsvir'),
        ),
        migrations.AlterField(
            model_name='birthdaypagesettings',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='birthday/hero/', verbose_name='Hero Şəkil'),
        ),
        migrations.AlterField(
            model_name='birthdaypagesettings',
            name='hero_subtitle',
            field=models.CharField(blank=True, default='🎉 Uşaqlarınız üçün ən xoş günlər', max_length=200, null=True, verbose_name='Hero Alt Başlıq'),
        ),
        migrations.AlterField(
            model_name='birthdaypagesettings',
            name='hero_title',
            field=models.CharField(blank=True, default='Doğum Gününü Alisa Club-da Unudulmaz Edin!', max_length=300, null=True, verbose_name='Hero Başlıq'),
        ),
        migrations.AlterField(
            model_name='birthdayreservation',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum Tarixi'),
        ),
        migrations.AlterField(
            model_name='birthdayreservation',
            name='child_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Uşağın Adı'),
        ),
        migrations.AlterField(
            model_name='birthdayreservation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='birthdayreservation',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Qeydlər'),
        ),
        migrations.AlterField(
            model_name='birthdayreservation',
            name='parent_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Valideynin Adı'),
        ),
        migrations.AlterField(
            model_name='birthdayreservation',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='birthdayreservationsettings',
            name='feature_1',
            field=models.CharField(blank=True, default='Unudulmaz doğum günü təşkil edin', max_length=200, null=True, verbose_name='Xüsusiyyət 1'),
        ),
        migrations.AlterField(
            model_name='birthdayreservationsettings',
            name='feature_2',
            field=models.CharField(blank=True, default='Rahat və əyləncəli mühit', max_length=200, null=True, verbose_name='Xüsusiyyət 2'),
        ),
        migrations.AlterField(
            model_name='birthdayreservationsettings',
            name='feature_3',
            field=models.CharField(blank=True, default='Foto və video çəkiliş imkanı', max_length=200, null=True, verbose_name='Xüsusiyyət 3'),
        ),
        migrations.AlterField(
            model_name='birthdayreservationsettings',
            name='feature_4',
            field=models.CharField(blank=True, default='Fərdi bəzək və proqram seçimi', max_length=200, null=True, verbose_name='Xüsusiyyət 4'),
        ),
        migrations.AlterField(
            model_name='birthdayreservationsettings',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='birthday/reservation/', verbose_name='Şəkil 1'),
        ),
        migrations.AlterField(
            model_name='birthdayreservationsettings',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='birthday/reservation/', verbose_name='Şəkil 2'),
        ),
        migrations.AlterField(
            model_name='birthdayreservationsettings',
            name='section_title',
            field=models.CharField(blank=True, default='Doğum Günü Rezervasiyası', max_length=200, null=True, verbose_name='Bölmə Başlığı'),
        ),
    ]
