# Generated by Django 5.2.5 on 2025-11-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0004_alter_birthdaygallery_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdaygallery',
            name='image',
            field=models.ImageField(blank=True, help_text='Tövsiyə olunan ölçü: 310x250 piksel', null=True, upload_to='birthday/gallery/', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='birthdaypagesettings',
            name='breadcrumb_image',
            field=models.ImageField(blank=True, help_text='Tövsiyə olunan ölçü: 1920x520 piksel', null=True, upload_to='birthday/breadcrumb/', verbose_name='Breadcrumb Arxa Fon'),
        ),
        migrations.AlterField(
            model_name='birthdaypagesettings',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Tövsiyə olunan ölçü: 543x339 piksel', null=True, upload_to='birthday/hero/', verbose_name='Hero Şəkil'),
        ),
        migrations.AlterField(
            model_name='birthdayreservationsettings',
            name='image_1',
            field=models.ImageField(blank=True, help_text='Tövsiyə olunan ölçü: 440x330 piksel', null=True, upload_to='birthday/reservation/', verbose_name='Şəkil 1'),
        ),
        migrations.AlterField(
            model_name='birthdayreservationsettings',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Tövsiyə olunan ölçü: 440x330 piksel', null=True, upload_to='birthday/reservation/', verbose_name='Şəkil 2'),
        ),
    ]
