# Generated by Django 5.2.5 on 2025-12-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0005_alter_birthdaygallery_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdayreservation',
            name='admin_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Admin Qeydləri'),
        ),
        migrations.AddField(
            model_name='birthdayreservation',
            name='event_date',
            field=models.DateField(blank=True, help_text='Doğum günü şənliyinin keçiriləcəyi tarix', null=True, verbose_name='Şənlik Tarixi'),
        ),
        migrations.AlterField(
            model_name='birthdayreservation',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Uşağın Doğum Tarixi'),
        ),
        migrations.AlterField(
            model_name='birthdayreservation',
            name='notes',
            field=models.TextField(blank=True, help_text='Müştərinin xüsusi istəkləri', null=True, verbose_name='Əlavə Qeydlər'),
        ),
    ]
