# Generated by Django 5.2.5 on 2025-12-02 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0006_birthdayreservation_admin_notes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BirthdayReservationSettings',
        ),
    ]
