# Generated by Django 5.2.5 on 2025-11-13 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breadcrumb_title', models.CharField(default='Haqqımızda', max_length=200, verbose_name='Breadcrumb Başlıq')),
                ('breadcrumb_description', models.TextField(default='Alisa Club uşaqların inkişafı, yaradıcılığı və öyrənməsini dəstəkləyən sevgi dolu bir mühit yaradır.', max_length=500, verbose_name='Breadcrumb Təsvir')),
                ('breadcrumb_image', models.ImageField(blank=True, null=True, upload_to='about/breadcrumb/', verbose_name='Breadcrumb Arxa Fon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə Tarixi')),
            ],
            options={
                'verbose_name': 'Haqqımızda Səhifə Parametrləri',
                'verbose_name_plural': 'Haqqımızda Səhifə Parametrləri',
            },
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Başlıq')),
                ('description', models.TextField(verbose_name='Təsvir')),
                ('image', models.ImageField(upload_to='about/sections/', verbose_name='Şəkil')),
                ('image_position', models.CharField(choices=[('left', 'Sol'), ('right', 'Sağ')], default='right', max_length=10, verbose_name='Şəkil Mövqeyi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma Tarixi')),
            ],
            options={
                'verbose_name': 'Haqqımızda Bölməsi',
                'verbose_name_plural': 'Haqqımızda Bölmələri',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/gallery/', verbose_name='Şəkil')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Başlıq')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma Tarixi')),
            ],
            options={
                'verbose_name': 'Qalereyası',
                'verbose_name_plural': 'Qalereyaları',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GallerySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Alisa Club-un rəngarəng dünyasına baxın!', max_length=300, verbose_name='Başlıq')),
                ('description', models.TextField(default='Kiçik ürəklərin böyük gülümsəmələri — hər anı sevgi ilə paylaşırıq', max_length=500, verbose_name='Təsvir')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə Tarixi')),
            ],
            options={
                'verbose_name': 'Qalereyası Bölməsi Parametrləri',
                'verbose_name_plural': 'Qalereyası Bölməsi Parametrləri',
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='İl')),
                ('title', models.CharField(max_length=200, verbose_name='Başlıq')),
                ('description', models.TextField(verbose_name='Təsvir')),
                ('image', models.ImageField(upload_to='about/timeline/', verbose_name='Şəkil')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma Tarixi')),
            ],
            options={
                'verbose_name': 'Tarixçə',
                'verbose_name_plural': 'Tarixçələr',
                'ordering': ['order', 'year'],
            },
        ),
        migrations.CreateModel(
            name='TimelineSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='Alisa Club tarixçəsi', max_length=200, verbose_name='Alt Başlıq')),
                ('title', models.CharField(default='İllərlə böyüyən sevgi və inkişafa səyahət', max_length=300, verbose_name='Başlıq')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə Tarixi')),
            ],
            options={
                'verbose_name': 'Tarixçə Bölməsi Parametrləri',
                'verbose_name_plural': 'Tarixçə Bölməsi Parametrləri',
            },
        ),
        migrations.CreateModel(
            name='AboutSectionFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Xüsusiyyət Mətni')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='about.aboutsection', verbose_name='Bölmə')),
            ],
            options={
                'verbose_name': 'Bölmə Xüsusiyyəti',
                'verbose_name_plural': 'Bölmə Xüsusiyyətləri',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SessionTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Seans Adı')),
                ('time', models.CharField(max_length=50, verbose_name='Vaxt')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_times', to='about.aboutsection', verbose_name='Bölmə')),
            ],
            options={
                'verbose_name': 'Seans Vaxtı',
                'verbose_name_plural': 'Seans Vaxtları',
                'ordering': ['order', 'id'],
            },
        ),
    ]
