# Generated by Django 5.2.5 on 2025-11-25 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpagesettings',
            name='breadcrumb_description',
            field=models.TextField(blank=True, default='Alisa Club uşaqların inkişafı, yaradıcılığı və öyrənməsini dəstəkləyən sevgi dolu bir mühit yaradır.', max_length=500, null=True, verbose_name='Breadcrumb Təsvir'),
        ),
        migrations.AlterField(
            model_name='aboutpagesettings',
            name='breadcrumb_title',
            field=models.CharField(blank=True, default='Haqqımızda', max_length=200, null=True, verbose_name='Breadcrumb Başlıq'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Təsvir'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/sections/', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='image_position',
            field=models.CharField(blank=True, choices=[('left', 'Sol'), ('right', 'Sağ')], default='right', max_length=10, null=True, verbose_name='Şəkil Mövqeyi'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Sıra'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='aboutsectionfeature',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Sıra'),
        ),
        migrations.AlterField(
            model_name='aboutsectionfeature',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='about.aboutsection', verbose_name='Bölmə'),
        ),
        migrations.AlterField(
            model_name='aboutsectionfeature',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Xüsusiyyət Mətni'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/gallery/', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Sıra'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='gallerysettings',
            name='description',
            field=models.TextField(blank=True, default='Kiçik ürəklərin böyük gülümsəmələri — hər anı sevgi ilə paylaşırıq', max_length=500, null=True, verbose_name='Təsvir'),
        ),
        migrations.AlterField(
            model_name='gallerysettings',
            name='title',
            field=models.CharField(blank=True, default='Alisa Club-un rəngarəng dünyasına baxın!', max_length=300, null=True, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='sessiontime',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Sıra'),
        ),
        migrations.AlterField(
            model_name='sessiontime',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_times', to='about.aboutsection', verbose_name='Bölmə'),
        ),
        migrations.AlterField(
            model_name='sessiontime',
            name='time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vaxt'),
        ),
        migrations.AlterField(
            model_name='sessiontime',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Seans Adı'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Təsvir'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/timeline/', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Sıra'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='İl'),
        ),
        migrations.AlterField(
            model_name='timelinesettings',
            name='subtitle',
            field=models.CharField(blank=True, default='Alisa Club tarixçəsi', max_length=200, null=True, verbose_name='Alt Başlıq'),
        ),
        migrations.AlterField(
            model_name='timelinesettings',
            name='title',
            field=models.CharField(blank=True, default='İllərlə böyüyən sevgi və inkişafa səyahət', max_length=300, null=True, verbose_name='Başlıq'),
        ),
    ]
