# Generated by Django 5.2.5 on 2025-11-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_aboutpagesettings_breadcrumb_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpagesettings',
            name='breadcrumb_image',
            field=models.ImageField(blank=True, help_text='Tövsiyə olunan ölçü: 1920x520 piksel', null=True, upload_to='about/breadcrumb/', verbose_name='Breadcrumb Arxa Fon'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='image',
            field=models.ImageField(blank=True, help_text='Tövsiyə olunan ölçü: 618x618 piksel', null=True, upload_to='about/sections/', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, help_text='Tövsiyə olunan ölçü: 290x253 piksel', null=True, upload_to='about/gallery/', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='image',
            field=models.ImageField(blank=True, help_text='Tövsiyə olunan ölçü: 300x150 piksel', null=True, upload_to='about/timeline/', verbose_name='Şəkil'),
        ),
    ]
