# Generated by Django 5.2.5 on 2025-11-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('is_read', models.BooleanField(default=False, verbose_name='Oxundu')),
                ('notes', models.TextField(blank=True, verbose_name='Admin Qeydləri')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Göndərilmə Tarixi')),
            ],
            options={
                'verbose_name': 'Əlaqə Mesajı',
                'verbose_name_plural': 'Əlaqə Mesajları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Bizimlə əlaqə', max_length=255, verbose_name='Başlıq')),
                ('subtitle', models.CharField(default='Alisa uşaqların öyrənməsi və inkişafı üçün qayğıkeş və mehriban bir mühit yaradır', max_length=255, verbose_name='Alt Başlıq')),
                ('image', models.ImageField(blank=True, null=True, upload_to='contact/', verbose_name='Şəkil')),
                ('phone', models.CharField(default='+994 (50) 123 45 67', max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(default='info@alisaclub.az', max_length=254, verbose_name='Email')),
                ('working_hours', models.CharField(default='Bazar ertəsi – Cümə, 09:00 – 18:00', max_length=200, verbose_name='İş Saatları')),
                ('map_embed', models.TextField(blank=True, help_text='Google Maps iframe src linki', verbose_name='Xəritə Embed Kodu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə Tarixi')),
            ],
            options={
                'verbose_name': 'Əlaqə Səhifə Parametrləri',
                'verbose_name_plural': 'Əlaqə Səhifə Parametrləri',
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Əlaqə (Köhnə)', 'verbose_name_plural': 'Əlaqə Bölməsi (Köhnə)'},
        ),
    ]
