# Generated by Django 5.2.5 on 2025-11-13 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactmessage_contactpagesettings_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactPageSettings',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Əlaqə', 'verbose_name_plural': 'Əlaqə Bölməsi'},
        ),
    ]
