# Generated by Django 5.2.5 on 2025-11-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_delete_contactpagesettings_alter_contact_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Soyad'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Mesaj'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Admin Qeydləri'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
    ]
