# Generated by Django 5.2.5 on 2025-11-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contactmessage_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, help_text='Tövsiyə olunan ölçü: 1920x520 piksel', null=True, upload_to='contact/'),
        ),
    ]
