# Generated by Django 5.2.7 on 2025-11-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon Nömrəsi')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-poçt')),
                ('address', models.CharField(blank=True, default='Atatür prospekti 1010', max_length=250, verbose_name='Ünvan')),
                ('filial_address', models.CharField(blank=True, max_length=250, verbose_name='Filial Ünvanı')),
                ('filial_phone', models.CharField(blank=True, max_length=50, verbose_name='Filial Telefon Nömrəsi')),
                ('work_days', models.CharField(blank=True, default='Bazar ertəsi – Cümə: 08:30 – 20:00', max_length=250, verbose_name='İş Günü')),
                ('map_embed', models.TextField(blank=True, help_text='Bütün iframe kodunu və ya embed linkini buraya yapışdırın', verbose_name='Google Maps Embed URL / iframe')),
            ],
            options={
                'verbose_name': 'Əlaqə Məlumatı',
                'verbose_name_plural': 'Əlaqə Məlumatları',
            },
        ),
        migrations.CreateModel(
            name='FooterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='Bizimlə Əlaqə Saxlayın', verbose_name='Footer Təsviri')),
                ('description', models.TextField(blank=True, verbose_name='Footer Təsvir')),
                ('copyright_text', models.CharField(blank=True, max_length=200, verbose_name='Footer Mətni')),
                ('creation_text', models.CharField(blank=True, max_length=100, verbose_name='Yaradıcı Mətn')),
                ('creation_url', models.URLField(blank=True, default='https://vrproduction.az/', verbose_name='Yaradıcı Link')),
            ],
            options={
                'verbose_name': 'Footer Məlumatı',
                'verbose_name_plural': 'Footer Məlumatları',
            },
        ),
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('home', 'Ana Səhifə'), ('about', 'Haqqımızda'), ('services', 'Xidmətlər (Siyahı Səhifəsi)'), ('blog', 'Blog (Siyahı Səhifəsi)'), ('contact', 'Əlaqə')], max_length=50, unique=True)),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('og_title', models.CharField(blank=True, max_length=255, null=True)),
                ('og_description', models.TextField(blank=True, null=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og-images/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='seo/logos/')),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('no_index', models.BooleanField(default=False)),
                ('no_follow', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Səhifə SEO',
                'verbose_name_plural': 'Səhifələr üçün SEO',
            },
        ),
        migrations.CreateModel(
            name='SiteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(blank=True, max_length=100, verbose_name='Alt mətn')),
                ('image', models.ImageField(upload_to='logos/', verbose_name='Logo Şəkli')),
            ],
            options={
                'verbose_name': 'Sayt Logo',
                'verbose_name_plural': 'Logo',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook Linki')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram Linki')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube Linki')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram Linki')),
            ],
        ),
    ]
