# Generated by Django 5.2.5 on 2025-11-13 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Uşağın adı')),
                ('birth_date', models.DateField(verbose_name='Doğum tarixi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Uşaq',
                'verbose_name_plural': 'Uşaqlar',
                'ordering': ['-birth_date'],
            },
        ),
        migrations.CreateModel(
            name='MedalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Medal adı')),
                ('icon', models.CharField(default='🏆', max_length=10, verbose_name='Emoji/İkon')),
                ('description', models.TextField(blank=True, verbose_name='Açıqlama')),
            ],
            options={
                'verbose_name': 'Medal Növü',
                'verbose_name_plural': 'Medal Növləri',
            },
        ),
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200, verbose_name='Tədbir adı')),
                ('event_date', models.DateField(verbose_name='Tədbir tarixi')),
                ('reason', models.TextField(blank=True, verbose_name='Qazanma səbəbi')),
                ('awarded_at', models.DateTimeField(auto_now_add=True, verbose_name='Verilmə tarixi')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medals', to='core.child')),
                ('medal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medaltype')),
            ],
            options={
                'verbose_name': 'Medal',
                'verbose_name_plural': 'Medallar',
                'ordering': ['-awarded_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Qeydiyyat tarixi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Valideyn Profili',
                'verbose_name_plural': 'Valideyn Profilləri',
            },
        ),
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200, verbose_name='Tədbir adı')),
                ('event_date', models.DateField(verbose_name='Tədbir tarixi')),
                ('status', models.CharField(choices=[('reserved', 'Rezerv edildi'), ('attended', 'İştirak etdi'), ('cancelled', 'Ləğv edildi')], default='reserved', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Qeydlər')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('children', models.ManyToManyField(to='core.child', verbose_name='İştirak edən uşaqlar')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.parentprofile')),
            ],
            options={
                'verbose_name': 'Tədbir Rezervasiyası',
                'verbose_name_plural': 'Tədbir Rezervasiyaları',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Təklif başlığı')),
                ('description', models.TextField(verbose_name='Açıqlama')),
                ('discount_percent', models.IntegerField(default=10, verbose_name='Endirim faizi')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Endirim kodu')),
                ('valid_from', models.DateField(verbose_name='Başlama tarixi')),
                ('valid_until', models.DateField(verbose_name='Bitmə tarixi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='core.parentprofile')),
            ],
            options={
                'verbose_name': 'Endirim',
                'verbose_name_plural': 'Endirimlər',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.parentprofile'),
        ),
    ]
