# Generated by Django 5.2.5 on 2025-11-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_child_medaltype_medal_parentprofile_eventbooking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.CharField(blank=True, default='Atatür prospekti 1010', max_length=250, null=True, verbose_name='Ünvan'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-poçt'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='filial_address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Filial Ünvanı'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='filial_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Filial Telefon Nömrəsi'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='map_embed',
            field=models.TextField(blank=True, help_text='Bütün iframe kodunu və ya embed linkini buraya yapışdırın', null=True, verbose_name='Google Maps Embed URL / iframe'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon Nömrəsi'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='work_days',
            field=models.CharField(blank=True, default='Bazar ertəsi – Cümə: 08:30 – 20:00', max_length=250, null=True, verbose_name='İş Günü'),
        ),
        migrations.AlterField(
            model_name='footerinfo',
            name='copyright_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Footer Mətni'),
        ),
        migrations.AlterField(
            model_name='footerinfo',
            name='creation_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Yaradıcı Mətn'),
        ),
        migrations.AlterField(
            model_name='footerinfo',
            name='creation_url',
            field=models.URLField(blank=True, default='https://vrproduction.az/', null=True, verbose_name='Yaradıcı Link'),
        ),
        migrations.AlterField(
            model_name='footerinfo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Footer Təsvir'),
        ),
        migrations.AlterField(
            model_name='footerinfo',
            name='title',
            field=models.TextField(blank=True, default='Bizimlə Əlaqə Saxlayın', null=True, verbose_name='Footer Təsviri'),
        ),
        migrations.AlterField(
            model_name='sitelogo',
            name='alt_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alt mətn'),
        ),
        migrations.AlterField(
            model_name='sitelogo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo Şəkli'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook Linki'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram Linki'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='Telegram Linki'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube Linki'),
        ),
    ]
