# Generated by Django 5.2.5 on 2025-12-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contactinfo_address_alter_contactinfo_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitelogo',
            name='header_logo',
            field=models.ImageField(blank=True, help_text='Header üçün qara rəngdə logo', null=True, upload_to='logos/', verbose_name='Header Logo (Qara rəng)'),
        ),
        migrations.AlterField(
            model_name='sitelogo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo Şəkli (Footer üçün - Ağ rəng)'),
        ),
    ]
