# Generated by Django 5.2.5 on 2025-12-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitelogo_header_logo_alter_sitelogo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerinfo',
            name='rights_reserved',
            field=models.CharField(blank=True, default='Bütün Hüquqlar Qorunur', max_length=100, null=True, verbose_name='Hüquqlar Mətni'),
        ),
    ]
