# Generated by Django 5.2.5 on 2025-12-02 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_footerinfo_rights_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='event_end_date',
            field=models.DateField(blank=True, help_text='Bir günlük tədbir üçün boş buraxın', null=True, verbose_name='Bitmə tarixi'),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='location',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Yer'),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Məhdudiyyət yoxdursa boş buraxın', null=True, verbose_name='Maksimum iştirakçı sayı'),
        ),
        migrations.AddField(
            model_name='medal',
            name='show_on_homepage',
            field=models.BooleanField(default=False, help_text='Seçilsə, bu medal ana səhifədə göstəriləcək', verbose_name='Ana səhifədə göstər'),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='children',
            field=models.ManyToManyField(blank=True, to='core.child', verbose_name='İştirak edən uşaqlar'),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi'),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='event_date',
            field=models.DateField(verbose_name='Başlama tarixi'),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Admin qeydləri'),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.parentprofile', verbose_name='Valideyn'),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Gözləyir'), ('confirmed', 'Təsdiqləndi'), ('attended', 'İştirak etdi'), ('cancelled', 'Ləğv edildi')], default='pending', help_text='Rezervasiyanın hazırkı vəziyyəti', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medals', to='core.child', verbose_name='Uşaq'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='event_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tədbir tarixi'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='event_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tədbir adı'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='medal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medaltype', verbose_name='Medal növü'),
        ),
    ]
