# Generated by Django 5.2.5 on 2025-12-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_eventbooking_event_end_date_eventbooking_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='photo',
            field=models.ImageField(blank=True, help_text='Uşağın profil şəkli', null=True, upload_to='children/', verbose_name='Şəkil'),
        ),
    ]
