# Generated by Django 5.2.5 on 2025-12-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_child_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['-valid_from'], 'verbose_name': 'Kampaniya', 'verbose_name_plural': 'Kampaniyalar'},
        ),
        migrations.RemoveField(
            model_name='discount',
            name='parent',
        ),
        migrations.AddField(
            model_name='discount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yaradılma tarixi'),
        ),
        migrations.AddField(
            model_name='discount',
            name='image',
            field=models.ImageField(blank=True, help_text='Tövsiyə olunan ölçü: 400x300 piksel', null=True, upload_to='campaigns/', verbose_name='Kampaniya şəkli'),
        ),
        migrations.AddField(
            model_name='discount',
            name='show_on_homepage',
            field=models.BooleanField(default=False, verbose_name='Ana səhifədə göstər'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, help_text='Məsələn: SUMMER2024', max_length=50, verbose_name='Endirim kodu'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_percent',
            field=models.IntegerField(default=10, help_text='Məsələn: 20 (20% endirim)', verbose_name='Endirim faizi'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Kampaniya başlığı'),
        ),
    ]
