# Generated by Django 5.2.5 on 2025-12-04 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_discount_options_remove_discount_parent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventBooking',
        ),
    ]
