# Generated by Django 5.2.7 on 2025-11-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Event Title')),
                ('event_description', models.TextField(blank=True, null=True, verbose_name='Event Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Image')),
            ],
        ),
    ]
