# Generated by Django 5.2.7 on 2025-11-11 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Alt başlıq')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('description', models.TextField(verbose_name='Əsas mətn')),
                ('image', models.ImageField(upload_to='about/', verbose_name='Şəkil')),
                ('stat_value', models.CharField(default='100%', max_length=20, verbose_name='Statistika dəyəri')),
                ('stat_text', models.CharField(default='Əla Nəticələr', max_length=100, verbose_name='Statistika mətni')),
                ('session_days', models.CharField(default='Bazar ertəsi – Cümə', max_length=100, verbose_name='Dərs günləri')),
            ],
            options={
                'verbose_name': 'Haqqımızda səhifəsi',
                'verbose_name_plural': 'Haqqımızda səhifəsi',
            },
        ),
        migrations.AlterModelOptions(
            name='hero',
            options={'verbose_name': 'Hero', 'verbose_name_plural': 'Hero'},
        ),
        migrations.CreateModel(
            name='SessionTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('morning', 'Səhər'), ('afternoon', 'Günorta'), ('evening', 'Axşam')], max_length=10, verbose_name='Dövr')),
                ('time_range', models.CharField(max_length=50, verbose_name='Vaxt aralığı')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_times', to='home.about')),
            ],
            options={
                'verbose_name': 'Dərs vaxtı',
                'verbose_name_plural': 'Dərs vaxtları',
                'ordering': ['period'],
            },
        ),
    ]
