# Generated by Django 5.2.7 on 2025-11-11 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_about_alter_hero_options_sessiontime'),
    ]

    operations = [
        migrations.CreateModel(
            name='KidContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Alisa Club Uşaq Kontenti', max_length=200, verbose_name='Başlıq')),
                ('description', models.TextField(default='Uşaqlar üçün yeni oyunlar, tapşırıqlar və yaradıcı fəaliyyətlər hər həftə', verbose_name='Açıqlama')),
                ('center_image', models.ImageField(help_text='Mərkəzdə görünəcək əsas şəkil', upload_to='kid_content/', verbose_name='Mərkəz şəkli')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Uşaq Kontenti Səhifəsi',
                'verbose_name_plural': 'Uşaq Kontenti Səhifəsi',
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Niyə Biz?', max_length=200, verbose_name='Başlıq')),
                ('subtitle', models.CharField(default='Əsas Dəyərlərimiz', max_length=200, verbose_name='Alt başlıq')),
                ('description', models.TextField(help_text='Bu hissə "Niyə Biz?" bölməsinin əsas mətnidir', verbose_name='Açıqlama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Niyə Biz? Səhifəsi',
                'verbose_name_plural': 'Niyə Biz? Səhifəsi',
            },
        ),
        migrations.CreateModel(
            name='KidContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlıq')),
                ('description', models.TextField(blank=True, verbose_name='Qısa mətn')),
                ('image', models.ImageField(upload_to='kid_content/items/', verbose_name='Şəkil')),
                ('position', models.CharField(choices=[('left', 'Sol sütun'), ('right', 'Sağ sütun')], max_length=10, verbose_name='Yerləşmə yeri')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('features', models.TextField(blank=True, help_text='Hər xüsusiyyəti yeni sətirdə yazın', verbose_name='Xüsusiyyətlər')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kid_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.kidcontent', verbose_name='Uşaq Kontenti')),
            ],
            options={
                'verbose_name': 'Uşaq Kontenti Maddəsi',
                'verbose_name_plural': 'Uşaq Kontenti Maddələri',
                'ordering': ['position', 'order'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlıq')),
                ('description', models.TextField(verbose_name='Açıqlama')),
                ('icon', models.ImageField(upload_to='why_choose_us/icons/', verbose_name='İkon')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('why_choose_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.whychooseus')),
            ],
            options={
                'verbose_name': 'Niyə Biz? Maddəsi',
                'verbose_name_plural': 'Niyə Biz? Maddələri',
                'ordering': ['order'],
            },
        ),
    ]
