# Generated by Django 5.2.7 on 2025-11-11 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_kidcontent_whychooseus_kidcontentitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Valideyn Rəyləri', max_length=200, verbose_name='Başlıq')),
                ('subtitle', models.CharField(default='Nə deyirlər', max_length=200, verbose_name='Alt başlıq')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tez-tez verilən suallar',
                'verbose_name_plural': 'Tez-tez verilən suallar',
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('comment', models.TextField(verbose_name='Rəy')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Ulduz'), (2, '2 Ulduz'), (3, '3 Ulduz'), (4, '4 Ulduz'), (5, '5 Ulduz')], default=5, verbose_name='Reytinq')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.faq', verbose_name='FAQ')),
            ],
            options={
                'verbose_name': 'Rəy',
                'verbose_name_plural': 'Rəylər',
                'ordering': ['order'],
            },
        ),
    ]
