# Generated by Django 5.2.7 on 2025-11-12 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_faq_faqitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlıq')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Alt başlıq')),
                ('description', models.TextField(verbose_name='Təsvir')),
                ('image', models.ImageField(blank=True, null=True, upload_to='birthday/', verbose_name='Şəkil')),
                ('button_text', models.CharField(default='Ətraflı Bax', max_length=50, verbose_name='Düymə mətni')),
            ],
            options={
                'verbose_name': 'Doğum Günü Şənliyi',
                'verbose_name_plural': 'Doğum Günü Şənlikləri',
            },
        ),
        migrations.CreateModel(
            name='BirthdayFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=10, verbose_name='İkon (emoji)')),
                ('text', models.CharField(max_length=200, verbose_name='Xüsusiyyət mətni')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='home.birthdayevent')),
            ],
            options={
                'verbose_name': 'Xüsusiyyət',
                'verbose_name_plural': 'Xüsusiyyətlər',
            },
        ),
    ]
