# Generated by Django 5.2.7 on 2025-11-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_birthdayevent_birthdayfeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='event_title',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Event Title'),
        ),
    ]
