# Generated by Django 5.2.5 on 2025-11-25 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_hero_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Əsas mətn'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='about',
            name='session_days',
            field=models.CharField(blank=True, default='Bazar ertəsi – Cümə', max_length=100, null=True, verbose_name='Dərs günləri'),
        ),
        migrations.AlterField(
            model_name='about',
            name='stat_text',
            field=models.CharField(blank=True, default='Əla Nəticələr', max_length=100, null=True, verbose_name='Statistika mətni'),
        ),
        migrations.AlterField(
            model_name='about',
            name='stat_value',
            field=models.CharField(blank=True, default='100%', max_length=20, null=True, verbose_name='Statistika dəyəri'),
        ),
        migrations.AlterField(
            model_name='about',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt başlıq'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='birthdayevent',
            name='button_text',
            field=models.CharField(blank=True, default='Ətraflı Bax', max_length=50, null=True, verbose_name='Düymə mətni'),
        ),
        migrations.AlterField(
            model_name='birthdayevent',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Təsvir'),
        ),
        migrations.AlterField(
            model_name='birthdayevent',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt başlıq'),
        ),
        migrations.AlterField(
            model_name='birthdayevent',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='birthdayfeature',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='home.birthdayevent'),
        ),
        migrations.AlterField(
            model_name='birthdayfeature',
            name='icon',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='İkon (emoji)'),
        ),
        migrations.AlterField(
            model_name='birthdayfeature',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Xüsusiyyət mətni'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='subtitle',
            field=models.CharField(blank=True, default='Nə deyirlər', max_length=200, null=True, verbose_name='Alt başlıq'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='title',
            field=models.CharField(blank=True, default='Valideyn Rəyləri', max_length=200, null=True, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Rəy'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='faq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.faq', verbose_name='FAQ'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ad Soyad'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Sıra'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 Ulduz'), (2, '2 Ulduz'), (3, '3 Ulduz'), (4, '4 Ulduz'), (5, '5 Ulduz')], default=5, null=True, verbose_name='Reytinq'),
        ),
        migrations.AlterField(
            model_name='kidcontent',
            name='center_image',
            field=models.ImageField(blank=True, help_text='Mərkəzdə görünəcək əsas şəkil', null=True, upload_to='kid_content/', verbose_name='Mərkəz şəkli'),
        ),
        migrations.AlterField(
            model_name='kidcontent',
            name='description',
            field=models.TextField(blank=True, default='Uşaqlar üçün yeni oyunlar, tapşırıqlar və yaradıcı fəaliyyətlər hər həftə', null=True, verbose_name='Açıqlama'),
        ),
        migrations.AlterField(
            model_name='kidcontent',
            name='title',
            field=models.CharField(blank=True, default='Alisa Club Uşaq Kontenti', max_length=200, null=True, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='kidcontentitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Qısa mətn'),
        ),
        migrations.AlterField(
            model_name='kidcontentitem',
            name='features',
            field=models.TextField(blank=True, help_text='Hər xüsusiyyəti yeni sətirdə yazın', null=True, verbose_name='Xüsusiyyətlər'),
        ),
        migrations.AlterField(
            model_name='kidcontentitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='kid_content/items/', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='kidcontentitem',
            name='kid_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.kidcontent', verbose_name='Uşaq Kontenti'),
        ),
        migrations.AlterField(
            model_name='kidcontentitem',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Sıra'),
        ),
        migrations.AlterField(
            model_name='kidcontentitem',
            name='position',
            field=models.CharField(blank=True, choices=[('left', 'Sol sütun'), ('right', 'Sağ sütun')], max_length=10, null=True, verbose_name='Yerləşmə yeri'),
        ),
        migrations.AlterField(
            model_name='kidcontentitem',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='sessiontime',
            name='about',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_times', to='home.about'),
        ),
        migrations.AlterField(
            model_name='sessiontime',
            name='period',
            field=models.CharField(blank=True, choices=[('morning', 'Səhər'), ('afternoon', 'Günorta'), ('evening', 'Axşam')], max_length=10, null=True, verbose_name='Dövr'),
        ),
        migrations.AlterField(
            model_name='sessiontime',
            name='time_range',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vaxt aralığı'),
        ),
        migrations.AlterField(
            model_name='whychooseus',
            name='description',
            field=models.TextField(blank=True, help_text='Bu hissə "Niyə Biz?" bölməsinin əsas mətnidir', null=True, verbose_name='Açıqlama'),
        ),
        migrations.AlterField(
            model_name='whychooseus',
            name='subtitle',
            field=models.CharField(blank=True, default='Əsas Dəyərlərimiz', max_length=200, null=True, verbose_name='Alt başlıq'),
        ),
        migrations.AlterField(
            model_name='whychooseus',
            name='title',
            field=models.CharField(blank=True, default='Niyə Biz?', max_length=200, null=True, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='whychooseusitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıqlama'),
        ),
        migrations.AlterField(
            model_name='whychooseusitem',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='why_choose_us/icons/', verbose_name='İkon'),
        ),
        migrations.AlterField(
            model_name='whychooseusitem',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Sıra'),
        ),
        migrations.AlterField(
            model_name='whychooseusitem',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='whychooseusitem',
            name='why_choose_us',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.whychooseus'),
        ),
    ]
