# Generated by Django 5.2.5 on 2025-11-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_about_description_alter_about_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default=1080, help_text='Şəklin formatlanacağı hündürlük (məsələn: 1080)', null=True, verbose_name='Şəkil Hündürlüyü (piksel)'),
        ),
        migrations.AddField(
            model_name='hero',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default=1920, help_text='Şəklin formatlanacağı en (məsələn: 1920)', null=True, verbose_name='Şəkil Eni (piksel)'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.ImageField(blank=True, help_text='Şəkil yüklənəndə yuxarıda göstərilən ölçüyə avtomatik formatlanacaq', null=True, upload_to='hero/', verbose_name='Şəkil'),
        ),
    ]
