# Generated by Django 5.2.5 on 2025-11-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_hero_image_height_hero_image_width_alter_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default=710, help_text='Şəklin formatlanacağı hündürlük (məsələn: 1080)', null=True, verbose_name='Şəkil Hündürlüyü (piksel)'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default=708, help_text='Şəklin formatlanacağı en (məsələn: 1920)', null=True, verbose_name='Şəkil Eni (piksel)'),
        ),
    ]
