# Generated by Django 5.2.5 on 2025-11-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_hero_image_height_alter_hero_image_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default=590, help_text='Şəklin formatlanacağı hündürlük (məsələn: 1080)', null=True, verbose_name='Şəkil Hündürlüyü (piksel)'),
        ),
        migrations.AddField(
            model_name='about',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default=590, help_text='Şəklin formatlanacağı en (məsələn: 1920)', null=True, verbose_name='Şəkil Eni (piksel)'),
        ),
        migrations.AddField(
            model_name='whychooseusitem',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default=214, help_text='Şəklin formatlanacağı hündürlük (məsələn: 1080)', null=True, verbose_name='Şəkil Hündürlüyü (piksel)'),
        ),
        migrations.AddField(
            model_name='whychooseusitem',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default=216, help_text='Şəklin formatlanacağı en (məsələn: 1920)', null=True, verbose_name='Şəkil Eni (piksel)'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, help_text='Şəkil yüklənəndə yuxarıda göstərilən ölçüyə avtomatik formatlanacaq', null=True, upload_to='about/', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='whychooseusitem',
            name='icon',
            field=models.ImageField(blank=True, help_text='Şəkil yüklənəndə yuxarıda göstərilən ölçüyə avtomatik formatlanacaq', null=True, upload_to='whyus/', verbose_name='Şəkil'),
        ),
    ]
