# Generated by Django 5.2.5 on 2025-11-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_about_image_height_about_image_width_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image_width',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='image_width',
        ),
        migrations.RemoveField(
            model_name='whychooseusitem',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='whychooseusitem',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, help_text='ölçü: 590X590', null=True, upload_to='about/', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.ImageField(blank=True, help_text='Tövsiyə olunan ölçü: 708x710 piksel', null=True, upload_to='hero/', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='whychooseusitem',
            name='icon',
            field=models.ImageField(blank=True, help_text='ölçü: 216x214 (enixhundurluyu)', null=True, upload_to='whyus/', verbose_name='Şəkil'),
        ),
    ]
