# Generated by Django 5.2.5 on 2025-11-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_about_image_height_remove_about_image_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdayevent',
            name='image',
            field=models.ImageField(blank=True, help_text='Tövsiyə olunan ölçü: 543x671 piksel', null=True, upload_to='birthday/', verbose_name='Şəkil'),
        ),
    ]
