# Generated by Django 5.2.5 on 2025-12-02 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_birthdayevent_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birthdayfeature',
            options={'ordering': ['order'], 'verbose_name': 'Xüsusiyyət', 'verbose_name_plural': 'Xüsusiyyətlər'},
        ),
        migrations.AddField(
            model_name='birthdayfeature',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Sıra'),
        ),
        migrations.AlterField(
            model_name='birthdayfeature',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='home.birthdayevent', verbose_name='Doğum Günü Şənliyi'),
        ),
        migrations.AlterField(
            model_name='birthdayfeature',
            name='icon',
            field=models.CharField(blank=True, default='🎈', help_text='Emoji daxil edin, məsələn: 🎈 🎮 🍰 🎁 📸 🎪', max_length=10, null=True, verbose_name='İkon (emoji)'),
        ),
    ]
