# Generated by Django 5.2.5 on 2025-12-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_birthdayfeature_options_birthdayfeature_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdayfeature',
            name='icon',
            field=models.CharField(blank=True, choices=[('🎈', '🎈 Şar'), ('🎉', '🎉 Konfeti'), ('🎂', '🎂 Tort'), ('🍰', '🍰 Keks'), ('🎁', '🎁 Hədiyyə'), ('🎮', '🎮 Oyun'), ('🎪', '🎪 Sirk'), ('🎨', '🎨 Rəsm'), ('🎭', '🎭 Maska'), ('📸', '📸 Foto'), ('🎵', '🎵 Musiqi'), ('🎊', '🎊 Bəzək'), ('🎀', '🎀 Lent'), ('🧁', '🧁 Muffin'), ('🍭', '🍭 Şirniyyat')], default='🎈', help_text='Siyahıdan emoji seçin', max_length=10, null=True, verbose_name='İkon'),
        ),
    ]
