# Generated by Django 5.2.5 on 2025-12-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_birthdayfeature_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayReservationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(blank=True, default='Doğum Günü Rezervasiyası', max_length=200, null=True, verbose_name='Bölmə Başlığı')),
                ('image_1', models.ImageField(blank=True, help_text='Rezervasiya formu yanında göstəriləcək şəkil. Tövsiyə olunan ölçü: 600x700 piksel', null=True, upload_to='birthday/reservation/', verbose_name='Əsas Şəkil')),
                ('feature_1', models.CharField(blank=True, default='Unudulmaz doğum günü təşkil edin', max_length=200, null=True, verbose_name='Xüsusiyyət 1')),
                ('feature_2', models.CharField(blank=True, default='Rahat və əyləncəli mühit', max_length=200, null=True, verbose_name='Xüsusiyyət 2')),
                ('feature_3', models.CharField(blank=True, default='Foto və video çəkiliş imkanı', max_length=200, null=True, verbose_name='Xüsusiyyət 3')),
                ('feature_4', models.CharField(blank=True, default='Fərdi bəzək və proqram seçimi', max_length=200, null=True, verbose_name='Xüsusiyyət 4')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə Tarixi')),
            ],
            options={
                'verbose_name': 'Rezervasiya Formu Parametrləri',
                'verbose_name_plural': 'Rezervasiya Formu Parametrləri',
            },
        ),
    ]
