# Generated by Django 5.2.5 on 2025-12-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_birthdayreservationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdayreservationsettings',
            name='image_1',
            field=models.ImageField(blank=True, help_text='Rezervasiya formu yanında göstəriləcək şəkil. Tövsiyə olunan ölçü: 440x330 piksel (En x Hündürlük)', null=True, upload_to='birthday/reservation/', verbose_name='Əsas Şəkil'),
        ),
    ]
