# Generated by Django 5.2.5 on 2025-12-02 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_birthdayreservationsettings_image_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthdayreservationsettings',
            name='image_1',
        ),
    ]
