# Generated by Django 5.2.5 on 2025-12-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_birthdayreservationsettings_image_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
        migrations.RemoveField(
            model_name='about',
            name='session_days',
        ),
        migrations.RemoveField(
            model_name='about',
            name='stat_text',
        ),
        migrations.RemoveField(
            model_name='about',
            name='stat_value',
        ),
        migrations.AddField(
            model_name='about',
            name='image_1',
            field=models.ImageField(blank=True, help_text='Tövsiyə olunan ölçü: 281x274 piksel', null=True, upload_to='about/', verbose_name='Şəkil 1 (Böyük)'),
        ),
        migrations.AddField(
            model_name='about',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Tövsiyə olunan ölçü: 281x274 piksel', null=True, upload_to='about/', verbose_name='Şəkil 2 (Kiçik üst)'),
        ),
        migrations.AddField(
            model_name='about',
            name='image_3',
            field=models.ImageField(blank=True, help_text='Tövsiyə olunan ölçü: 281x274 piksel', null=True, upload_to='about/', verbose_name='Şəkil 3 (Kiçik orta)'),
        ),
        migrations.AddField(
            model_name='about',
            name='image_4',
            field=models.ImageField(blank=True, help_text='Tövsiyə olunan ölçü: 281x274 piksel', null=True, upload_to='about/', verbose_name='Şəkil 4 (Kiçik alt)'),
        ),
        migrations.AddField(
            model_name='about',
            name='stat_1_text',
            field=models.CharField(blank=True, default='Açıq Hava Fəaliyyətləri', max_length=100, null=True, verbose_name='Statistika 1 - Mətn'),
        ),
        migrations.AddField(
            model_name='about',
            name='stat_1_value',
            field=models.CharField(blank=True, default='75', max_length=20, null=True, verbose_name='Statistika 1 - Dəyər'),
        ),
        migrations.AddField(
            model_name='about',
            name='stat_2_text',
            field=models.CharField(blank=True, default='Sevgi Dolu Müəllimlər', max_length=100, null=True, verbose_name='Statistika 2 - Mətn'),
        ),
        migrations.AddField(
            model_name='about',
            name='stat_2_value',
            field=models.CharField(blank=True, default='23', max_length=20, null=True, verbose_name='Statistika 2 - Dəyər'),
        ),
    ]
