# Generated by Django 5.2.5 on 2025-11-12 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogKateqoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Kateqoriya Adı')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('yaradilma_tarixi', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma Tarixi')),
            ],
            options={
                'verbose_name': 'Blog Kateqoriyası',
                'verbose_name_plural': 'Blog Kateqoriyaları',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basliq', models.CharField(max_length=200, verbose_name='Başlıq')),
                ('alt_basliq', models.CharField(blank=True, max_length=300, verbose_name='Alt Başlıq')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('qisa_mezmun', models.TextField(max_length=500, verbose_name='Qısa Məzmun')),
                ('tam_mezmun', models.TextField(verbose_name='Tam Məzmun')),
                ('media_tipi', models.CharField(choices=[('sekil', 'Şəkil'), ('video', 'Video'), ('audio', 'Audio'), ('qalereyasi', 'Şəkil Qalereyası'), ('yoxdur', 'Media Yoxdur')], default='sekil', max_length=20, verbose_name='Media Tipi')),
                ('sekil', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Şəkil')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL (YouTube/Vimeo)')),
                ('audio_url', models.URLField(blank=True, verbose_name='Audio URL (SoundCloud)')),
                ('tarix', models.DateField(verbose_name='Tarix')),
                ('muellif', models.CharField(blank=True, max_length=100, verbose_name='Müəllif')),
                ('muellif_sekli', models.ImageField(blank=True, null=True, upload_to='blog/muellif/', verbose_name='Müəllif Şəkli')),
                ('muellif_haqqinda', models.TextField(blank=True, verbose_name='Müəllif Haqqında')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('cox_oxunan', models.BooleanField(default=False, verbose_name='Çox Oxunan')),
                ('yaradilma_tarixi', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma Tarixi')),
                ('yenileme_tarixi', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə Tarixi')),
                ('kateqoriya', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloglar', to='blog.blogkateqoriya', verbose_name='Kateqoriya')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Bloglar',
                'ordering': ['-tarix', '-yaradilma_tarixi'],
            },
        ),
        migrations.CreateModel(
            name='BlogQalereyasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sekil', models.ImageField(upload_to='blog/qalereyasi/', verbose_name='Şəkil')),
                ('basliq', models.CharField(blank=True, max_length=100, verbose_name='Başlıq')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qalereyasi', to='blog.blog', verbose_name='Blog')),
            ],
            options={
                'verbose_name': 'Blog Qalereyası',
                'verbose_name_plural': 'Blog Qalereyaları',
                'ordering': ['sira', 'id'],
            },
        ),
    ]
