# Generated by Django 4.2.7 on 2025-08-13 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kateqoriya Adı')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Təsvir')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Rəng')),
                ('icon', models.CharField(default='fas fa-folder', max_length=50, verbose_name='İkon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blog Kateqoriyası',
                'verbose_name_plural': 'Blog Kateqoriyaları',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlıq')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(max_length=300, verbose_name='Qısa Məzmun')),
                ('content', models.TextField(verbose_name='Məzmun')),
                ('featured_image', models.ImageField(blank=True, upload_to='blog_images/', verbose_name='Əsas Şəkil')),
                ('status', models.CharField(choices=[('draft', 'Qaralama'), ('published', 'Dərc Edildi'), ('archived', 'Arxivləndi')], default='draft', max_length=20, verbose_name='Status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Seçilmiş')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='Etiketlər')),
                ('read_time', models.IntegerField(default=5, verbose_name='Oxuma Müddəti (dəqiqə)')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Baxış Sayı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Dərc Tarixi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Müəllif')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogcategory', verbose_name='Kateqoriya')),
            ],
            options={
                'verbose_name': 'Blog Yazısı',
                'verbose_name_plural': 'Blog Yazıları',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Şərh')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Təsdiqləndi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Müəllif')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost', verbose_name='Yazı')),
            ],
            options={
                'verbose_name': 'Blog Şərhi',
                'verbose_name_plural': 'Blog Şərhləri',
                'ordering': ['-created_at'],
            },
        ),
    ]
