# Generated by Django 5.2.5 on 2025-11-12 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kateqoriya Adı')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma Tarixi')),
            ],
            options={
                'verbose_name': 'Blog Kateqoriyası',
                'verbose_name_plural': 'Blog Kateqoriyaları',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SidebarGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sidebar/gallery/', verbose_name='Şəkil')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Başlıq')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma Tarixi')),
            ],
            options={
                'verbose_name': 'Sidebar Qalereyası',
                'verbose_name_plural': 'Sidebar Qalereyaları',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='blog',
            name='kateqoriya',
        ),
        migrations.RemoveField(
            model_name='blogqalereyasi',
            name='blog',
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Bloglar'},
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='muellif',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='muellif_haqqinda',
            new_name='author_bio',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='yaradilma_tarixi',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='tarix',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='tam_mezmun',
            new_name='full_content',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='sekil',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='aktiv',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='cox_oxunan',
            new_name='is_featured',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='qisa_mezmun',
            new_name='short_content',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='alt_basliq',
            new_name='subtitle',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='basliq',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='yenileme_tarixi',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='media_tipi',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='muellif_sekli',
        ),
        migrations.AddField(
            model_name='blog',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/author/', verbose_name='Müəllif Şəkli'),
        ),
        migrations.AddField(
            model_name='blog',
            name='media_type',
            field=models.CharField(choices=[('image', 'Şəkil'), ('video', 'Video'), ('audio', 'Audio'), ('gallery', 'Şəkil Qalereyası'), ('none', 'Media Yoxdur')], default='image', max_length=20, verbose_name='Media Tipi'),
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='blog.blogcategory', verbose_name='Kateqoriya'),
        ),
        migrations.CreateModel(
            name='BlogGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/gallery/', verbose_name='Şəkil')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Başlıq')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='blog.blog', verbose_name='Blog')),
            ],
            options={
                'verbose_name': 'Blog Qalereyası',
                'verbose_name_plural': 'Blog Qalereyaları',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='BlogKateqoriya',
        ),
        migrations.DeleteModel(
            name='BlogQalereyasi',
        ),
    ]
