# Generated by Django 5.2.5 on 2025-11-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogcategory_sidebargallery_remove_blog_kateqoriya_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breadcrumb_title', models.CharField(default='Bloqlarımız', max_length=200, verbose_name='Breadcrumb Başlıq')),
                ('breadcrumb_description', models.TextField(default='"Alisa Club" uşaqların inkişafı və öyrənməsi üçün sevgi dolu və hərtərəfli yanaşma təqdim edir', max_length=500, verbose_name='Breadcrumb Təsvir')),
                ('breadcrumb_image', models.ImageField(blank=True, null=True, upload_to='blog/breadcrumb/', verbose_name='Breadcrumb Arxa Fon Şəkli')),
                ('widget_title', models.CharField(default='Gəlin bir yerdə möhtəşəm işlər yaradaq', max_length=200, verbose_name='Widget Başlıq')),
                ('widget_description', models.TextField(default='Uşaq bağçası ilə bağlı ən son xəbərlər, dəstək və məsləhətlərdən xəbərdar olun.', max_length=500, verbose_name='Widget Təsvir')),
                ('widget_button_text', models.CharField(default='Üzv Ol', max_length=50, verbose_name='Widget Düymə Mətni')),
                ('widget_button_url', models.CharField(default='/registration/', max_length=200, verbose_name='Widget Düymə URL')),
                ('widget_background_image', models.ImageField(blank=True, null=True, upload_to='blog/widget/', verbose_name='Widget Arxa Fon Şəkli')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə Tarixi')),
            ],
            options={
                'verbose_name': 'Blog Səhifə Parametrləri',
                'verbose_name_plural': 'Blog Səhifə Parametrləri',
            },
        ),
    ]
