# Generated by Django 5.2.5 on 2025-11-12 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpagesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tədbir Adı')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(max_length=500, verbose_name='Qısa Təsvir')),
                ('full_description', models.TextField(verbose_name='Tam Təsvir')),
                ('event_date', models.DateTimeField(verbose_name='Tədbir Tarixi')),
                ('location', models.CharField(max_length=300, verbose_name='Yer')),
                ('map_url', models.URLField(blank=True, verbose_name='Xəritə URL (Google Maps)')),
                ('coordinator_name', models.CharField(blank=True, max_length=100, verbose_name='Koordinator Adı')),
                ('coordinator_phone', models.CharField(blank=True, max_length=20, verbose_name='Koordinator Telefon')),
                ('coordinator_email', models.EmailField(blank=True, max_length=254, verbose_name='Koordinator Email')),
                ('image', models.ImageField(upload_to='events/', verbose_name='Tədbir Şəkli')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Əsas Tədbir')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma Tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə Tarixi')),
            ],
            options={
                'verbose_name': 'Tədbir',
                'verbose_name_plural': 'Tədbirlər',
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='EventGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Sual')),
                ('answer', models.TextField(verbose_name='Cavab')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='blog.event', verbose_name='Tədbir')),
            ],
            options={
                'verbose_name': 'Tədbir Bələdçisi',
                'verbose_name_plural': 'Tədbir Bələdçiləri',
                'ordering': ['order', 'id'],
            },
        ),
    ]
