# Generated by Django 5.2.5 on 2025-11-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_event_eventguide'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_in_footer',
            field=models.BooleanField(default=False, verbose_name='Footer-də Göstər'),
        ),
    ]
