# Generated by Django 5.2.5 on 2025-11-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_event_show_in_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageBlogSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Son Xəbərlər', max_length=200, verbose_name='Bölmə Başlığı')),
                ('description', models.TextField(default='"Alisa Club"da təqdim olunan fəaliyyətləri və yenilikləri daim genişləndiririk', max_length=500, verbose_name='Bölmə Təsviri')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə Tarixi')),
            ],
            options={
                'verbose_name': 'Ana Səhifə Blog Parametrləri',
                'verbose_name_plural': 'Ana Səhifə Blog Parametrləri',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='homepage_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ana Səhifə Sırası'),
        ),
        migrations.AddField(
            model_name='blog',
            name='show_on_homepage',
            field=models.BooleanField(default=False, verbose_name='Ana Səhifədə Göstər'),
        ),
    ]
