# Generated by Django 5.2.5 on 2025-11-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_homepageblogsettings_blog_homepage_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='show_in_sidebar',
            field=models.BooleanField(default=False, verbose_name='Sidebar-da Göstər'),
        ),
        migrations.AddField(
            model_name='blog',
            name='sidebar_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sidebar Sırası'),
        ),
    ]
