# Generated by Django 5.2.5 on 2025-11-25 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_show_in_sidebar_blog_sidebar_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='audio_url',
            field=models.URLField(blank=True, null=True, verbose_name='Audio URL (SoundCloud)'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Müəllif'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author_bio',
            field=models.TextField(blank=True, null=True, verbose_name='Müəllif Haqqında'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='blog.blogcategory', verbose_name='Kateqoriya'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Tarix'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='full_content',
            field=models.TextField(blank=True, null=True, verbose_name='Tam Məzmun'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='homepage_order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Ana Səhifə Sırası'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Şəkil'), ('video', 'Video'), ('audio', 'Audio'), ('gallery', 'Şəkil Qalereyası'), ('none', 'Media Yoxdur')], default='image', max_length=20, null=True, verbose_name='Media Tipi'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_content',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Qısa Məzmun'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='sidebar_order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Sidebar Sırası'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Alt Başlıq'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL (YouTube/Vimeo)'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kateqoriya Adı'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='bloggallery',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='blog.blog', verbose_name='Blog'),
        ),
        migrations.AlterField(
            model_name='bloggallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/gallery/', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='bloggallery',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Sıra'),
        ),
        migrations.AlterField(
            model_name='bloggallery',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='blogpagesettings',
            name='breadcrumb_description',
            field=models.TextField(blank=True, default='"Alisa Club" uşaqların inkişafı və öyrənməsi üçün sevgi dolu və hərtərəfli yanaşma təqdim edir', max_length=500, null=True, verbose_name='Breadcrumb Təsvir'),
        ),
        migrations.AlterField(
            model_name='blogpagesettings',
            name='breadcrumb_title',
            field=models.CharField(blank=True, default='Bloqlarımız', max_length=200, null=True, verbose_name='Breadcrumb Başlıq'),
        ),
        migrations.AlterField(
            model_name='blogpagesettings',
            name='widget_button_text',
            field=models.CharField(blank=True, default='Üzv Ol', max_length=50, null=True, verbose_name='Widget Düymə Mətni'),
        ),
        migrations.AlterField(
            model_name='blogpagesettings',
            name='widget_button_url',
            field=models.CharField(blank=True, default='/registration/', max_length=200, null=True, verbose_name='Widget Düymə URL'),
        ),
        migrations.AlterField(
            model_name='blogpagesettings',
            name='widget_description',
            field=models.TextField(blank=True, default='Uşaq bağçası ilə bağlı ən son xəbərlər, dəstək və məsləhətlərdən xəbərdar olun.', max_length=500, null=True, verbose_name='Widget Təsvir'),
        ),
        migrations.AlterField(
            model_name='blogpagesettings',
            name='widget_title',
            field=models.CharField(blank=True, default='Gəlin bir yerdə möhtəşəm işlər yaradaq', max_length=200, null=True, verbose_name='Widget Başlıq'),
        ),
        migrations.AlterField(
            model_name='event',
            name='coordinator_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Koordinator Email'),
        ),
        migrations.AlterField(
            model_name='event',
            name='coordinator_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Koordinator Adı'),
        ),
        migrations.AlterField(
            model_name='event',
            name='coordinator_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Koordinator Telefon'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tədbir Tarixi'),
        ),
        migrations.AlterField(
            model_name='event',
            name='full_description',
            field=models.TextField(blank=True, null=True, verbose_name='Tam Təsvir'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Tədbir Şəkli'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Yer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='map_url',
            field=models.URLField(blank=True, null=True, verbose_name='Xəritə URL (Google Maps)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Qısa Təsvir'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tədbir Adı'),
        ),
        migrations.AlterField(
            model_name='eventguide',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Cavab'),
        ),
        migrations.AlterField(
            model_name='eventguide',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='blog.event', verbose_name='Tədbir'),
        ),
        migrations.AlterField(
            model_name='eventguide',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Sıra'),
        ),
        migrations.AlterField(
            model_name='eventguide',
            name='question',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Sual'),
        ),
        migrations.AlterField(
            model_name='homepageblogsettings',
            name='description',
            field=models.TextField(blank=True, default='"Alisa Club"da təqdim olunan fəaliyyətləri və yenilikləri daim genişləndiririk', max_length=500, null=True, verbose_name='Bölmə Təsviri'),
        ),
        migrations.AlterField(
            model_name='homepageblogsettings',
            name='title',
            field=models.CharField(blank=True, default='Son Xəbərlər', max_length=200, null=True, verbose_name='Bölmə Başlığı'),
        ),
        migrations.AlterField(
            model_name='sidebargallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sidebar/gallery/', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='sidebargallery',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Sıra'),
        ),
        migrations.AlterField(
            model_name='sidebargallery',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Başlıq'),
        ),
    ]
