# Generated by Django 5.2.5 on 2025-11-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_audio_url_alter_blog_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author_image',
            field=models.ImageField(blank=True, help_text='Tövsiyə olunan ölçü: 180x180 piksel', null=True, upload_to='blog/author/', verbose_name='Müəllif Şəkli'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, help_text='Tövsiyə olunan ölçü: 1300x703 piksel', null=True, upload_to='blog/', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='bloggallery',
            name='image',
            field=models.ImageField(blank=True, help_text='Tövsiyə olunan ölçü: 100x100 piksel', null=True, upload_to='blog/gallery/', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='blogpagesettings',
            name='breadcrumb_image',
            field=models.ImageField(blank=True, help_text='Tövsiyə olunan ölçü: 1920x520 piksel', null=True, upload_to='blog/breadcrumb/', verbose_name='Breadcrumb Arxa Fon Şəkli'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Tövsiyə olunan ölçü: 1290x640 piksel', null=True, upload_to='events/', verbose_name='Tədbir Şəkli'),
        ),
        migrations.AlterField(
            model_name='sidebargallery',
            name='image',
            field=models.ImageField(blank=True, help_text='Tövsiyə olunan ölçü: 100x100 piksel', null=True, upload_to='sidebar/gallery/', verbose_name='Şəkil'),
        ),
    ]
