# Generated by Django 5.2.5 on 2025-12-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blog_author_image_alter_blog_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_end_date',
            field=models.DateTimeField(blank=True, help_text='Bir günlük tədbir üçün boş buraxın', null=True, verbose_name='Bitmə Tarixi'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Başlama Tarixi'),
        ),
    ]
