# Generated by Django 5.2.5 on 2025-12-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_event_event_end_date_alter_event_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_on_hero',
            field=models.BooleanField(default=False, verbose_name='Hero Slider-də Göstər'),
        ),
    ]
