# Generated by Django 5.2.5 on 2025-12-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_event_show_on_hero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='event',
            name='show_on_homepage',
            field=models.BooleanField(default=False, verbose_name='Ana Səhifədə Göstər'),
        ),
    ]
