# Generated by Django 4.2.7 on 2025-08-13 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('address', models.TextField(verbose_name='Ünvan')),
                ('emergency_contact', models.CharField(max_length=100, verbose_name='Təcili əlaqə şəxsi')),
                ('emergency_phone', models.CharField(max_length=20, verbose_name='Təcili əlaqə telefonu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Üzv Profili',
                'verbose_name_plural': 'Üzv Profilləri',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('basic', 'Əsas'), ('premium', 'Premium'), ('vip', 'VIP')], default='basic', max_length=20, verbose_name='Üzvlük növü')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('inactive', 'Qeyri-aktiv'), ('suspended', 'Dayandırılmış')], default='active', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Başlama tarixi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Bitmə tarixi')),
                ('discount_percentage', models.IntegerField(default=0, verbose_name='Endirim faizi')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='membership.memberprofile')),
            ],
            options={
                'verbose_name': 'Üzvlük',
                'verbose_name_plural': 'Üzvlüklər',
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('surname', models.CharField(max_length=100, verbose_name='Soyad')),
                ('birth_date', models.DateField(verbose_name='Doğum tarixi')),
                ('gender', models.CharField(choices=[('M', 'Oğlan'), ('F', 'Qız')], max_length=1, verbose_name='Cins')),
                ('allergies', models.TextField(blank=True, verbose_name='Allergiyalar')),
                ('special_notes', models.TextField(blank=True, verbose_name='Xüsusi qeydlər')),
                ('photo', models.ImageField(blank=True, upload_to='children_photos/', verbose_name='Şəkil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='membership.memberprofile')),
            ],
            options={
                'verbose_name': 'Uşaq',
                'verbose_name_plural': 'Uşaqlar',
                'ordering': ['name'],
            },
        ),
    ]
