# Generated by Django 4.2.7 on 2025-08-13 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kateqoriya adı')),
                ('description', models.TextField(blank=True, verbose_name='Təsvir')),
                ('color', models.CharField(default='#10b981', max_length=7, verbose_name='Rəng')),
                ('icon', models.CharField(default='fas fa-book', max_length=50, verbose_name='İkon')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Məzmun Kateqoriyası',
                'verbose_name_plural': 'Məzmun Kateqoriyaları',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KidsMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlıq')),
                ('description', models.TextField(verbose_name='Təsvir')),
                ('material_type', models.CharField(choices=[('pdf', 'PDF Fayl'), ('video', 'Video'), ('audio', 'Audio'), ('game', 'Oyun'), ('coloring', 'Rəngləmə Səhifəsi'), ('story', 'Nağıl'), ('activity', 'Fəaliyyət'), ('worksheet', 'İş Vərəqi')], max_length=20, verbose_name='Material növü')),
                ('age_group', models.CharField(choices=[('0-3', '0-3 yaş'), ('3-6', '3-6 yaş'), ('6-9', '6-9 yaş'), ('9-12', '9-12 yaş'), ('12+', '12+ yaş')], max_length=10, verbose_name='Yaş qrupu')),
                ('difficulty_level', models.CharField(choices=[('easy', 'Asan'), ('medium', 'Orta'), ('hard', 'Çətin')], default='easy', max_length=10, verbose_name='Çətinlik səviyyəsi')),
                ('file', models.FileField(blank=True, upload_to='kids_materials/', verbose_name='Fayl')),
                ('image', models.ImageField(blank=True, upload_to='kids_materials/images/', verbose_name='Şəkil')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL')),
                ('content', models.TextField(blank=True, verbose_name='Məzmun')),
                ('instructions', models.TextField(blank=True, verbose_name='Təlimatlar')),
                ('learning_objectives', models.TextField(blank=True, verbose_name='Öyrənmə məqsədləri')),
                ('duration_minutes', models.IntegerField(blank=True, null=True, verbose_name='Müddət (dəqiqə)')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium məzmun')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Seçilmiş məzmun')),
                ('download_count', models.IntegerField(default=0, verbose_name='Yükləmə sayı')),
                ('view_count', models.IntegerField(default=0, verbose_name='Baxış sayı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='kids_content.contentcategory', verbose_name='Kateqoriya')),
            ],
            options={
                'verbose_name': 'Uşaq Materialı',
                'verbose_name_plural': 'Uşaq Materialları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='kids_content.kidsmaterial', verbose_name='Material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'Material Yükləməsi',
                'verbose_name_plural': 'Material Yükləmələri',
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Qiymət')),
                ('comment', models.TextField(blank=True, verbose_name='Şərh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='kids_content.kidsmaterial', verbose_name='Material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'Material Qiyməti',
                'verbose_name_plural': 'Material Qiymətləri',
                'ordering': ['-created_at'],
                'unique_together': {('material', 'user')},
            },
        ),
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Başlanmayıb'), ('in_progress', 'Davam edir'), ('completed', 'Tamamlandı')], default='not_started', max_length=20, verbose_name='Status')),
                ('progress_percentage', models.IntegerField(default=0, verbose_name='Tərəqqi faizi')),
                ('time_spent_minutes', models.IntegerField(default=0, verbose_name='Sərf edilən vaxt (dəqiqə)')),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='kids_content.kidsmaterial', verbose_name='Material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'Öyrənmə Tərəqqisi',
                'verbose_name_plural': 'Öyrənmə Tərəqqiləri',
                'ordering': ['-last_accessed'],
                'unique_together': {('user', 'material')},
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='kids_content.kidsmaterial', verbose_name='Material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'Sevimli',
                'verbose_name_plural': 'Sevimlilər',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'material')},
            },
        ),
    ]
